### PR TITLE
Updates to the supported languages list

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Updates to the supported languages list. Adds missing languages as well as put the list in alphabetical order.

### CODE REVIEW

**Comment by flosse** [comment]
Could you rebase this PR? thx.

**Comment by gilbertohasnofb** [comment]
I will rebase this once the Fortran PR is merged as to avoid rebasing it twice.

**Comment by gilbertohasnofb** [comment]
@flosse this should be ready to be merged. Once you are done with that, I will open a PR to fix the LaTeX regex.

**Comment by gilbertohasnofb** [comment]
@flosse Would it be possible for you to take another look at this PR? It is ready to be merged.

**Comment by flosse** [comment]
thx!

**Comment by gilbertohasnofb** [comment]
Thanks! I will submit one more PR to fix that LaTeX regex.

**Pull request merged**
