### PR TITLE
Setup Mega-Linter Github Action

### PR DESCRIPTION
**Pull request by nvuillam**
I needed a coffeescript repo to validate [Mega-Linter](https://github.com/nvuillam/mega-linter#readme) coffeescript compliance :)

I recently added sloc to one of my repos so it seemed a good candidate ^^

Once I succeed (or not) to verify Mega-Linter is ok, you can decide if you want to keep it here or not , as u prefer :)

- Added mega-linter.yml github action
- Fixed lint errors and typos
- Added cspell whitelist words
- Added Mega-Linter badge on README (visible only when PR would be merged)

You can check Mega-Linter reports:
- https://github.com/nvuillam/sloc/actions/runs/355690909: Full code scan
- https://github.com/nvuillam/sloc/actions/runs/355741688: Only PR diff scan

If you want to auto-apply fixes during CI, you may need to [define a PAT in secrets](https://github.com/nvuillam/mega-linter#apply-fixes)

I suggest "Squash & merge" option for this PR :)

### CODE REVIEW

**Comment by nvuillam** [comment]
now ready :)

**Comment by flosse** [comment]
Thank for you PR.
What is `.cspell.json ` for?

**Comment by nvuillam** [comment]
It is the config file for cSpell linter : https://github.com/streetsidesoftware/cspell/tree/master/packages/cspell

( that's the linter that allowed me to detect typos )
It requires  words not in their dictionaries, like family names,  to be defined in local config file. 

I can also disable it if you think it is too much ^^

**Review by flosse — APPROVED** [review]

**Comment by flosse** [comment]
thx!

**Comment by nvuillam** [comment]
you're welcome 👍 by the way your dependency status badge seems down ^^

**Pull request merged**
