### PR TITLE
add support for .cxx, .hxx extensions

### PR DESCRIPTION
**Pull request by Liamsi**

### CODE REVIEW

**Comment by flosse** [comment]
thx!

**Comment by Liamsi** [comment]
Thank you, too. Do you already know when you will create the next release? (I know these 4 words do not really justify a new release)

**Comment by flosse** [comment]
> when you will create the next release? 

As soon as #48 and #49 are fixed. I'm quite busy right now, so feel free to contribute :)

**Comment by Liamsi** [comment]
I have a fix for #48 and will provide a pull request as soon as possible.

**Pull request merged**
