### PR TITLE
Add elixir support

### PR DESCRIPTION
**Pull request by MiniAppleTheApple**
Elixir is a dynamic, functional, fault-torelant language that runs on BEAM, designed for concurrency.
https://elixir-lang.org/

### CODE REVIEW

**Review by flosse — CHANGES_REQUESTED** [review]
Would you mind to also extend the `extensions` array and mention elixir in the `README.md`?

**Comment by zwrawr** [comment]
Elixer has a notion of documentation in the code with `@doc` and `@moduledoc` blocks. You could debate about whether these are true comments. But for SLOC, I think it makes more sense to count them as comments than as source.

**Comment by flosse** [comment]
I'm sorry, it might be a misunderstanding, I'm talking about this here:

https://github.com/flosse/sloc/blob/2cb07c17715d1036cf0965411d5a06a8ed92627f/src/sloc.coffee#L265

**Comment by flosse** [comment]
...ah, I didn't see the new PR :see_no_evil:

**Comment by flosse** [comment]
Closing in favor of #148

**Pull request closed without merging**
