### PR TITLE
Feature/restore back cli options

### PR DESCRIPTION
**Pull request by domengasperlin**
It seems release is failing due to failing test [here](https://github.com/Homebrew/homebrew-core/actions/runs/7381740793/job/20080671025?pr=158728) https://github.com/Homebrew/homebrew-core/pull/158728

The test is checking if sloc works with csv format option https://github.com/Homebrew/homebrew-core/blob/171e50bca163025fd40fde21629cc667da49c77c/Formula/s/sloc.rb#L23

Options functionality was broken with commander v7.0.0 release. 

## From migration guide for commander lib

Use the .opts() method to access the options. This is available on any command but is used most with the program.
Details: https://github.com/tj/commander.js/releases/tag/v7.0.0

This restores different options functionality.

### CODE REVIEW

**Comment by flosse** [comment]
Thx!

**Comment by flosse** [comment]
Let me know if I should create a release :)

**Comment by domengasperlin** [comment]
> Let me know if I should create a release :)

Please yes, test output now also matches 
image
image

**Comment by chenrui333** [comment]
Can we cut a pre-release or release for testing? There is no clean way to apply this PR change.

**Comment by rhysperry111** [comment]
Just bumping this - a release would be really happy because the tool is currently completely broken.

**Comment by flosse** [comment]
> Just bumping this - a release would be really helpful because the tool is currently completely broken.

sure :+1: Should be online now.

**Pull request merged**
