### PR TITLE
added jsx as known file extension

### PR DESCRIPTION
**Pull request by capaj**
so that we can count lines in our react projects as well

### CODE REVIEW

**Comment by flosse** [comment]
thx!

**Comment by jonrh** [comment]
Any ETA on when this will be available on npm?

**Comment by flosse** [comment]
as soon #49 is fixed ;-)

**Comment by jonrh** [comment]
Ahh got ya. What I did in the meantime was making a copy of my project and renaming all .jsx files to .js. Verified one sample JSX file and the numbers matched up. Stellar, keep up the good work!

**Comment by flosse** [comment]
> What I did in the meantime was making a copy of my project and renaming all .jsx files to .js.

what about using the `--alias` option?

**Comment by jonrh** [comment]
I tried `sloc -a jsx=js` (--alias too). It yielded the same results as simply running `sloc` without parameters.

**Pull request merged**
