### PR TITLE
Fix regression in 0.3.0

### LINKED ISSUE #137: 0.3.0 regression test failure
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  ==> /opt/homebrew/Cellar/sloc/0.3.0/bin/sloc --format=csv .
  /opt/homebrew/Cellar/sloc/0.3.0/libexec/lib/node_modules/sloc/node_modules/readdirp/index.js:264
      throw new TypeError('readdirp: root argument must be a string. Usage: readdirp(root, options)');
      ^
  
  TypeError: readdirp: root argument must be a string. Usage: readdirp(root, options)
      at readdirp (/opt/homebrew/Cellar/sloc/0.3.0/libexec/lib/node_modules/sloc/node_modules/readdirp/index.js:264:11)
      at readDir (/opt/homebrew/Cellar/sloc/0.3.0/libexec/lib/node_modules/sloc/lib/cli.js:176:12)
      at /opt/homebrew/Cellar/sloc/0.3.0/libexec/lib/node_modules/sloc/lib/cli.js:194:16
      at FSReqCallback.oncomplete (node:fs:200:5)
  
  Node.js v20.7.0
  
  Error: sloc: failed
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6256768201/job/16988130801
relates to Homebrew/homebrew-core#144381

### PR DESCRIPTION
**Pull request by sebamarynissen**
This fixes #137.

### CODE REVIEW

**Comment by flosse** [comment]
Shouldn't we rather adapt the code instead of reverting to an outdated library?

**Comment by flosse** [comment]
BTW: `readdirp` seems to be outdated anyway :rofl:

**Comment by flosse** [comment]
What do you think about using [glob](https://www.npmjs.com/package/glob)?

**Comment by chenrui333** [comment]
this patch does not work for [my PR](https://github.com/Homebrew/homebrew-core/pull/144381), ie, the `format` option still does not work.

```
$ sloc --format=csv .

---------- Result ------------

            Physical :  4
              Source :  4
             Comment :  0
 Single-line comment :  0
       Block comment :  0
               Mixed :  0
 Empty block comment :  0
               Empty :  0
               To Do :  0

Number of files read :  1

----------------------------
```

**Comment by flosse** [comment]
... this should now be obsolete, since #143 is merged.
Thanks anyway!

**Pull request closed without merging**
